### ISSUE TITLE
ModuleNotFoundError: No module named 'third_libs'

### ISSUE THREAD

**Issue by ZhouFangru** [MrTornado24/Next3D#18]
Thank you very much for your work, but something wrong when running the following commands:

```
cd dataset_preprocessing/ffhq
python preprocess_in_the_wild.py --indir=INPUT_IMAGE_FOLDER
```

```
Traceback (most recent call last):
  File "/media/cfs/zhoufangru/workspace/3D_restruction/Next3D/dataset_preprocessing/ffhq/faceverse/fit_imgs_offline_cuda.py", line 14, in <module>
    from data_reader import ImageReader_FFHQ as ImageReader
  File "/media/cfs/zhoufangru/workspace/3D_restruction/Next3D/dataset_preprocessing/ffhq/faceverse/data_reader.py", line 8, in <module>
    from third_libs.OpenSeeFace.tracker import Tracker
ModuleNotFoundError: No module named 'third_libs'
```

Where can I download third_libs.

**Comment by ZhouFangru** [comment]
https://github.com/LizhenWangT/FaceVerse/tree/main/third_libs

> hi, did you solve this problem?

**Comment by ZhouFangru** [comment]
@xLuge https://github.com/LizhenWangT/FaceVerse/tree/main/third_libs
