### ISSUE TITLE
parameter packs not expanded with ‘...’ in `preprocess_in_the_wild.py`

### ISSUE THREAD

**Issue by SCZwangxiao** [MrTornado24/Next3D#26]
When running
```python
command = f"python fit_imgs_offline_cuda.py --input {os.path.join(args.indir, 'crop')} --res_folder {os.path.join(args.indir, 'gaze_results')}"
```

We get:
```bash
[i 0810 18:42:45.557166 80 compiler.py:956] Jittor(1.3.8.5) src: /mnt3/xiao.wang/miniconda3/envs/deep3d/lib/python3.7/site-packages/jittor
[i 0810 18:42:45.561653 80 compiler.py:957] g++ at /usr/bin/g++(11.4.0)
[i 0810 18:42:45.561714 80 compiler.py:958] cache_path: /home/xiao.wang/.cache/jittor/jt1.3.8/g++11.4.0/py3.7.12/Linux-5.15.0-5xf5/IntelRXeonRPlax86/default
[i 0810 18:42:45.566649 80 __init__.py:411] Found /usr/local/cuda/bin/nvcc(11.6.55) at /usr/local/cuda/bin/nvcc.
[i 0810 18:42:45.574267 80 __init__.py:411] Found addr2line(2.38) at /usr/bin/addr2line.
[i 0810 18:42:45.690106 80 compiler.py:1011] cuda key:cu11.6.55_sm_86
[i 0810 18:42:46.181445 80 __init__.py:227] Total mem: 739.62GB, using 16 procs for compiling.
/usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
  435 |         function(_Functor&& __f)
      |                                                                                                                                                 ^ 
/usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
/usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
  530 |         operator=(_Functor&& __f)
      |                                                                                                                                                  ^ 
/usr/include/c++/11/bits/std_function.h:530:146: note:         ‘_ArgTypes’
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/mnt3/xiao.wang/miniconda3/envs/deep3d/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/mnt3/xiao.wang/miniconda3/envs/deep3d/lib/python3.7/site-packages/jittor_utils/__init__.py", line 197, in do_compile
    return cc.cache_compile(cmd, cache_path, jittor_path)
RuntimeError: [f 0810 18:42:49.087578 80 log.cc:608] Check failed ret(256) == 0(0) Run cmd failed: "/usr/local/cuda/bin/nvcc"  "/mnt3/xiao.wang/miniconda3/envs/deep3d/lib/python3.7/site-packages/jittor/src/misc/nan_checker.cu"     -std=c++14 -Xcompiler -fPIC  -Xcompiler -march=native  -Xcompiler -fdiagnostics-color=always   -I"/mnt3/xiao.wang/miniconda3/envs/deep3d/lib/python3.7/site-packages/jittor/src" -I/mnt3/xiao.wang/miniconda3/envs/deep3d/include/python3.7m -I/mnt3/xiao.wang/miniconda3/envs/deep3d/include/python3.7m -DHAS_CUDA -DIS_CUDA -I"/usr/local/cuda/include" -I"/mnt3/xiao.wang/miniconda3/envs/deep3d/lib/python3.7/site-packages/jittor/extern/cuda/inc"   -I"/home/xiao.wang/.cache/jittor/jt1.3.8/g++11.4.0/py3.7.12/Linux-5.15.0-5xf5/IntelRXeonRPlax86/default/cu11.6.55_sm_86"   -O2   -c -o "/home/xiao.wang/.cache/jittor/jt1.3.8/g++11.4.0/py3.7.12/Linux-5.15.0-5xf5/IntelRXeonRPlax86/default/cu11.6.55_sm_86/obj_files/nan_checker.cu.o" -x cu --cudart=shared -ccbin="/usr/bin/g++"   -w  -I"/mnt3/xiao.wang/miniconda3/envs/deep3d/lib/python3.7/site-packages/jittor/extern/cuda/inc" 
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "fit_imgs_offline_cuda.py", line 5, in <module>
    import jittor as jt
  File "/mnt3/xiao.wang/miniconda3/envs/deep3d/lib/python3.7/site-packages/jittor/__init__.py", line 18, in <module>
    from . import compiler
  File "/mnt3/xiao.wang/miniconda3/envs/deep3d/lib/python3.7/site-packages/jittor/compiler.py", line 1354, in <module>
    compile(cc_path, cc_flags+opt_flags, files, 'jittor_core'+extension_suffix)
  File "/mnt3/xiao.wang/miniconda3/envs/deep3d/lib/python3.7/site-packages/jittor/compiler.py", line 151, in compile
    jit_utils.run_cmds(cmds, cache_path, jittor_path, "Compiling "+base_output)
  File "/mnt3/xiao.wang/miniconda3/envs/deep3d/lib/python3.7/site-packages/jittor_utils/__init__.py", line 251, in run_cmds
    for i,_ in enumerate(p.imap_unordered(do_compile, cmds)):
  File "/mnt3/xiao.wang/miniconda3/envs/deep3d/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
RuntimeError: [f 0810 18:42:49.087578 80 log.cc:608] Check failed ret(256) == 0(0) Run cmd failed: "/usr/local/cuda/bin/nvcc"  "/mnt3/xiao.wang/miniconda3/envs/deep3d/lib/python3.7/site-packages/jittor/src/misc/nan_checker.cu"     -std=c++14 -Xcompiler -fPIC  -Xcompiler -march=native  -Xcompiler -fdiagnostics-color=always   -I"/mnt3/xiao.wang/miniconda3/envs/deep3d/lib/python3.7/site-packages/jittor/src" -I/mnt3/xiao.wang/miniconda3/envs/deep3d/include/python3.7m -I/mnt3/xiao.wang/miniconda3/envs/deep3d/include/python3.7m -DHAS_CUDA -DIS_CUDA -I"/usr/local/cuda/include" -I"/mnt3/xiao.wang/miniconda3/envs/deep3d/lib/python3.7/site-packages/jittor/extern/cuda/inc"   -I"/home/xiao.wang/.cache/jittor/jt1.3.8/g++11.4.0/py3.7.12/Linux-5.15.0-5xf5/IntelRXeonRPlax86/default/cu11.6.55_sm_86"   -O2   -c -o "/home/xiao.wang/.cache/jittor/jt1.3.8/g++11.4.0/py3.7.12/Linux-5.15.0-5xf5/IntelRXeonRPlax86/default/cu11.6.55_sm_86/obj_files/nan_checker.cu.o" -x cu --cudart=shared -ccbin="/usr/bin/g++"   -w  -I"/mnt3/xiao.wang/miniconda3/envs/deep3d/lib/python3.7/site-packages/jittor/extern/cuda/inc" 

```

**Comment by SCZwangxiao** [comment]
The problem lies in the compatibility issues jittor package.
Just install jittor from source.
